# For parameter descriptions, please refer to the template parameter files for each node.
go1_0165:
  ekf_local:
    ros__parameters:
      # Basics
      frequency: 30.0
      sensor_timeout: 0.1
      two_d_mode: true
      publish_tf: true
      publish_acceleration: false
      
      # Frames
      map_frame: autonomy_park
      odom_frame: go1_0165/odom
      base_link_frame: go1_0165/base_link
      world_frame: go1_0165/odom
      
      # Sensor fusion configuration - which variables each source will contribute to
      # [x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw, ax, ay, az]
      
      # Platform odometry: Use position, orientation, and velocities
      odom0: platform/odometry
      odom0_config: [false, false, false,  # x, y, z
                    false, false, false,  # roll, pitch, yaw
                    true, true, false,   # vx, vy, vz
                    false, false, true,  # vroll, vpitch, vyaw
                    false, false, false] # ax, ay, az
      odom0_queue_size: 10
      odom0_nodelay: false
      odom0_differential: false
      odom0_relative: false
      
      # IMU data: Use orientation, angular velocities, and linear accelerations
      imu0: sensors/imu_0/data
      imu0_config: [false, false, false,  # x, y, z
                   true, true, true,      # roll, pitch, yaw
                   false, false, false,   # vx, vy, vz
                   true, true, true,      # vroll, vpitch, vyaw
                   true, true, true]      # ax, ay, az
      imu0_queue_size: 10
      imu0_nodelay: false
      imu0_differential: false
      imu0_relative: false
      imu0_remove_gravitational_acceleration: true
      
      # Filter parameters
      use_control: false
      process_noise_covariance: [0.05, 0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                                0,    0.05, 0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                                0,    0,    0.06, 0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                                0,    0,    0,    0.03, 0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                                0,    0,    0,    0,    0.03, 0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                                0,    0,    0,    0,    0,    0.06, 0,     0,     0,    0,    0,    0,    0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0.025, 0,     0,    0,    0,    0,    0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,     0.025, 0,    0,    0,    0,    0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,     0,     0.04, 0,    0,    0,    0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,     0,     0,    0.01, 0,    0,    0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0.01, 0,    0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0.02, 0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0.01, 0,    0,
                                0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0.01, 0,
                                0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0.015]
                                
      initial_estimate_covariance: [1e-9, 0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                   0,    1e-9, 0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                   0,    0,    1e-9, 0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                   0,    0,    0,    1e-9, 0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                   0,    0,    0,    0,    1e-9, 0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                   0,    0,    0,    0,    0,    1e-9, 0,    0,    0,    0,     0,     0,     0,    0,    0,
                                   0,    0,    0,    0,    0,    0,    1e-9, 0,    0,    0,     0,     0,     0,    0,    0,
                                   0,    0,    0,    0,    0,    0,    0,    1e-9, 0,    0,     0,     0,     0,    0,    0,
                                   0,    0,    0,    0,    0,    0,    0,    0,    1e-9, 0,     0,     0,     0,    0,    0,
                                   0,    0,    0,    0,    0,    0,    0,    0,    0,    1e-9,  0,     0,     0,    0,    0,
                                   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     1e-9,  0,     0,    0,    0,
                                   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     1e-9,  0,    0,    0,
                                   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     1e-9, 0,    0,
                                   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    1e-9, 0,
                                   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    1e-9]

  ekf_global:
    ros__parameters:
      frequency: 30.0
      sensor_timeout: 0.1
      two_d_mode: false
      publish_tf: true
      publish_acceleration: false
      
      # Frames - note world_frame is set to map for the global EKF
      map_frame: autonomy_park
      odom_frame: go1_0165/odom
      base_link_frame: go1_0165/base_link
      world_frame: autonomy_park
      
      # Output from the first EKF
      odom0: odometry/local
      odom0_config: [false, false, false,   # x, y, z
                    false, false, false,   # roll, pitch, yaw
                    true, true, false,    # vx, vy, vz
                    false, false, true,   # vroll, vpitch, vyaw
                    false, false, false]  # ax, ay, az
      odom0_queue_size: 10
      odom0_nodelay: false
      odom0_differential: false
      odom0_relative: false
      
      # Transformed GPS data
      odom1: odometry/gps
      odom1_config: [true, true, false,   # x, y, z
                    false, false, false,  # roll, pitch, yaw
                    false, false, false,  # vx, vy, vz
                    false, false, false,  # vroll, vpitch, vyaw
                    false, false, false]  # ax, ay, az
      odom1_queue_size: 10
      odom1_nodelay: false
      odom1_differential: false
      odom1_relative: false
      
      # Slightly higher process noise for the global filter
      process_noise_covariance: [0.1, 0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                                0,    0.1,  0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                                0,    0,    0.1,  0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                                0,    0,    0,    0.05, 0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                                0,    0,    0,    0,    0.05, 0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                                0,    0,    0,    0,    0,    0.1,  0,     0,     0,    0,    0,    0,    0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0.05,  0,     0,    0,    0,    0,    0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,     0.05,  0,    0,    0,    0,    0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,     0,     0.1,  0,    0,    0,    0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,     0,     0,    0.02, 0,    0,    0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0.02, 0,    0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0.04, 0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0.02, 0,    0,
                                0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0.02, 0,
                                0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0.03]

  navsat_transform:
    ros__parameters:
      frequency: 10.0
      delay: 0.0
      
      # GPS topic
      magnetic_declination_radians: 0.1115
      yaw_offset: 0.0
      zero_altitude: false
      broadcast_utm_transform: true
      publish_filtered_gps: true
      use_odometry_yaw: false
      wait_for_datum: true
      
      # GPS frame IDs
      gps_frame_id: go1_0165/navsat_link
      map_frame: autonomy_park
      odom_frame: go1_0165/odom
      base_link_frame: go1_0165/base_link
      world_frame: autonomy_park
      
      # Input topics
      imu_topic: sensors/imu_0/data
      gps_topic: sensors/gps/fix
      odometry_topic: odometry/local
      
      # Datum for local reference frame (example for a location - adjust to your specific needs)
      # Format: [latitude, longitude, altitude]
      # This defines the origin of your local coordinate system
      datum: [29.628158, -82.360346, -0.602196554855]
