microstrain_inertial_driver:
  ros__parameters:
    port: "/dev/microstrain_main"
    aux_port: "/dev/ttyACM1"
    baudrate: 115200
    imu_frame_id: "imu_link"

    use_enu_frame: true
    imu_data_rate: 100

    publish_mount_to_frame_id_transform: False

    debug: false
    diagnostics: true
